"""add sla settings

Revision ID: 3e7d7ffbbc8a
Revises: 9c1942d66734
Create Date: 2026-03-08 13:32:45.059058

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3e7d7ffbbc8a'
down_revision: Union[str, Sequence[str], None] = '9c1942d66734'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('firm_settings')
    op.create_index('idx_notice_dashboard', 'notices', ['status', 'due_date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_notice_dashboard', table_name='notices')
    op.create_table('firm_settings',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('auto_generate_draft', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('auto_generate_risk', sa.BOOLEAN(), server_default=sa.text('true'), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=True),
    sa.Column('auto_assign_high_risk', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=True),
    sa.Column('high_risk_threshold', sa.DOUBLE_PRECISION(precision=53), server_default=sa.text('4.00'), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name=op.f('firm_settings_pkey'))
    )
    # ### end Alembic commands ###
