"""Recreate notice_risk_metadata

Revision ID: 682aaa9edd42
Revises: c05012afd778
Create Date: 2026-02-27 19:23:41.012775

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '682aaa9edd42'
down_revision: Union[str, Sequence[str], None] = 'c05012afd778'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notice_risk_metadata',
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('severity_score', sa.Integer(), nullable=False),
    sa.Column('days_remaining', sa.Integer(), nullable=False),
    sa.Column('repeat_flag', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('last_updated', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notice_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notice_risk_metadata')
    # ### end Alembic commands ###
