"""Add missing columns to sections_master

Revision ID: 7d51e9325c15
Revises: 7e91925a42ca
Create Date: 2026-02-27 17:54:34.319589

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '7d51e9325c15'
down_revision: Union[str, Sequence[str], None] = '7e91925a42ca'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('appeal_versions')
    op.drop_table('notice_assignments')
    op.drop_table('notice_risk_metadata')
    op.drop_table('draft_versions')
    op.alter_column('firms', 'created_at',
               existing_type=postgresql.TIMESTAMP(timezone=True),
               type_=sa.TIMESTAMP(),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.drop_index(op.f('ix_firms_id'), table_name='firms')
    op.create_index(op.f('ix_notice_timeline_id'), 'notice_timeline', ['id'], unique=False)
    op.alter_column('notices', 'act_name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('sections_master', 'category',
               existing_type=sa.VARCHAR(),
               nullable=True,
               existing_server_default=sa.text("'section'::character varying"))
    op.drop_index(op.f('idx_sections_act_section'), table_name='sections_master')
    op.drop_index(op.f('idx_sections_penalty_flag'), table_name='sections_master')
    op.drop_constraint(op.f('unique_act_section'), 'sections_master', type_='unique')
    op.drop_column('sections_master', 'exposure_type')
    op.drop_column('sections_master', 'updated_at')
    op.drop_column('sections_master', 'related_penalty_reference')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections_master', sa.Column('related_penalty_reference', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('sections_master', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=True))
    op.add_column('sections_master', sa.Column('exposure_type', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_unique_constraint(op.f('unique_act_section'), 'sections_master', ['act_name', 'section_reference'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('idx_sections_penalty_flag'), 'sections_master', ['penalty_flag'], unique=False)
    op.create_index(op.f('idx_sections_act_section'), 'sections_master', ['act_name', 'section_reference'], unique=False)
    op.alter_column('sections_master', 'category',
               existing_type=sa.VARCHAR(),
               nullable=False,
               existing_server_default=sa.text("'section'::character varying"))
    op.alter_column('notices', 'act_name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_notice_timeline_id'), table_name='notice_timeline')
    op.create_index(op.f('ix_firms_id'), 'firms', ['id'], unique=False)
    op.alter_column('firms', 'created_at',
               existing_type=sa.TIMESTAMP(),
               type_=postgresql.TIMESTAMP(timezone=True),
               existing_nullable=True,
               existing_server_default=sa.text('now()'))
    op.create_table('draft_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('notice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('introduction', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('facts_summary', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('legal_position', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('section_reference', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('prayer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], name=op.f('draft_versions_notice_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('draft_versions_pkey')),
    sa.UniqueConstraint('notice_id', 'version_number', name=op.f('unique_notice_version'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    op.create_table('notice_risk_metadata',
    sa.Column('notice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('severity_score', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('days_remaining', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('repeat_flag', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('risk_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False),
    sa.Column('last_updated', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], name=op.f('notice_risk_metadata_notice_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('notice_id', name=op.f('notice_risk_metadata_pkey'))
    )
    op.create_table('notice_assignments',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('notice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('assigned_to', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('assigned_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], name=op.f('notice_assignments_assigned_to_fkey')),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], name=op.f('notice_assignments_notice_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('notice_assignments_pkey'))
    )
    op.create_table('appeal_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('notice_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('version_number', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('background', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('grounds', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('prayer', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], name=op.f('appeal_versions_notice_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('appeal_versions_pkey')),
    sa.UniqueConstraint('notice_id', 'version_number', name=op.f('unique_notice_appeal_version'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
