"""Add missing column exposure_type to sections_master

Revision ID: 96e7613b4ebb
Revises: 7d51e9325c15
Create Date: 2026-02-27 17:59:44.328760

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '96e7613b4ebb'
down_revision: Union[str, Sequence[str], None] = '7d51e9325c15'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections_master', sa.Column('exposure_type', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections_master', 'exposure_type')
    # ### end Alembic commands ###
