"""Recreate notice_assignments

Revision ID: 9c1942d66734
Revises: 23476ee1fb0d
Create Date: 2026-03-01 06:35:01.335035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c1942d66734'
down_revision: Union[str, Sequence[str], None] = '23476ee1fb0d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notice_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('assigned_to', sa.Integer(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('assigned_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to'], ['users.id'], ),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notice_assignments_id'), 'notice_assignments', ['id'], unique=False)
    op.drop_constraint(op.f('unique_notice_appeal_version'), 'appeal_versions', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('unique_notice_appeal_version'), 'appeal_versions', ['notice_id', 'version_number'], postgresql_nulls_not_distinct=False)
    op.drop_index(op.f('ix_notice_assignments_id'), table_name='notice_assignments')
    op.drop_table('notice_assignments')
    # ### end Alembic commands ###
