"""add updated raw_text to notices

Revision ID: a3117622ed3f
Revises: a6044ea47b9e
Create Date: 2026-02-18 07:55:04.492266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a3117622ed3f'
down_revision: Union[str, Sequence[str], None] = 'a6044ea47b9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('raw_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notices', 'raw_text')
    # ### end Alembic commands ###
