"""add new notice classification fields

Revision ID: af5a9edbc91d
Revises: 23c30d0d316c
Create Date: 2026-02-16 19:50:34.658127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af5a9edbc91d'
down_revision: Union[str, Sequence[str], None] = '23c30d0d316c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notices', sa.Column('section', sa.String(), nullable=True))
    op.add_column('notices', sa.Column('assessment_year', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('notices', 'assessment_year')
    op.drop_column('notices', 'section')
    # ### end Alembic commands ###
