"""add assigned_to to clients

Revision ID: bd1cfd88b3ef
Revises: 0bf3cbc6b390
Create Date: 2026-02-15 10:17:19.961151

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd1cfd88b3ef'
down_revision: Union[str, Sequence[str], None] = '0bf3cbc6b390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clients', sa.Column('assigned_to', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'clients', 'users', ['assigned_to'], ['id'])
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.drop_constraint(None, 'clients', type_='foreignkey')
    op.drop_column('clients', 'assigned_to')
    # ### end Alembic commands ###
