"""add act metadata to document_chunks

Revision ID: bdee6aedd4a4
Revises: 4035f54b74e4
Create Date: 2026-02-16 06:53:41.580244

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bdee6aedd4a4'
down_revision: Union[str, Sequence[str], None] = '4035f54b74e4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document_chunks', sa.Column('act_name', sa.String(), nullable=False))
    op.add_column('document_chunks', sa.Column('section_number', sa.String(), nullable=True))
    op.add_column('document_chunks', sa.Column('year', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('document_chunks', 'year')
    op.drop_column('document_chunks', 'section_number')
    op.drop_column('document_chunks', 'act_name')
    # ### end Alembic commands ###
