"""Remove full_text from sections_master

Revision ID: c05012afd778
Revises: c278b68c5c22
Create Date: 2026-02-27 18:09:30.265225

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c05012afd778'
down_revision: Union[str, Sequence[str], None] = 'c278b68c5c22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections_master', 'full_text')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections_master', sa.Column('full_text', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
