"""Add missing column related_penalty_reference to sections_master

Revision ID: c278b68c5c22
Revises: 96e7613b4ebb
Create Date: 2026-02-27 18:04:06.496591

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c278b68c5c22'
down_revision: Union[str, Sequence[str], None] = '96e7613b4ebb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('sections_master', sa.Column('related_penalty_reference', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sections_master', 'related_penalty_reference')
    # ### end Alembic commands ###
