"""Recreate draft_versions table

Revision ID: ce6f91f282f0
Revises: 682aaa9edd42
Create Date: 2026-02-27 19:38:54.481099

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce6f91f282f0'
down_revision: Union[str, Sequence[str], None] = '682aaa9edd42'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('draft_versions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('notice_id', sa.Integer(), nullable=False),
    sa.Column('version_number', sa.Integer(), nullable=False),
    sa.Column('introduction', sa.Text(), nullable=False),
    sa.Column('facts_summary', sa.Text(), nullable=False),
    sa.Column('legal_position', sa.Text(), nullable=False),
    sa.Column('section_reference', sa.Text(), nullable=False),
    sa.Column('prayer', sa.Text(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
    sa.ForeignKeyConstraint(['notice_id'], ['notices.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('draft_versions')
    # ### end Alembic commands ###
