"""add firms table

Revision ID: e753c7f410e3
Revises: a3117622ed3f
Create Date: 2026-02-18 11:50:11.391924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e753c7f410e3'
down_revision: Union[str, Sequence[str], None] = 'a3117622ed3f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('firms',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('license_type', sa.String(), nullable=True),
    sa.Column('trial_expiry', sa.DateTime(), nullable=True),
    sa.Column('max_users', sa.Integer(), nullable=True),
    sa.Column('max_ai_queries_per_month', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_firms_id'), 'firms', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_firms_id'), table_name='firms')
    op.drop_table('firms')
    # ### end Alembic commands ###
